# Generated by Django 4.2.6 on 2023-12-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beranda',
            new_name='Home',
        ),
    ]
